export default {
   perso:[
    {
        id:1,
        nom:"albedo",
        img:"/img/genshinImg/Albedo.png",
    },
    {
        id:2,
        nom:"Alhaitham",
        img:"/img/genshinImg/Alhaitham.png",
    },
    {
        id:3,
        nom:"Aloy",
        img:"/img/genshinImg/Aloy.png",
    },
    {
        id:4,
        nom:"Amber",
        img:"/img/genshinImg/Amber.png",
    },
    {
        id:5,
        nom:"Ayaka",
        img:"/img/genshinImg/Ayaka.png",
    },
    {
        id:6,
        nom:"Ayato",
        img:"/img/genshinImg/Ayato.png",
    },
    {
        id:7,
        nom:"Barbara",
        img:"/img/genshinImg/Barbara.png",
    },
    {
        id:8,
        nom:"Berdou",
        img:"/img/genshinImg/Beidou.png",
    },
    {
        id:9,
        nom:"Bennett",
        img:"/img/genshinImg/Bennett.png",
    },
    {
        id:10,
        nom:"Candace",
        img:"/img/genshinImg/Candace.png",
    },
    {
        id:11,
        nom:"Childe",
        img:"/img/genshinImg/Childe.png",
    },
    {
        id:12,
        nom:"Chongyun",
        img:"/img/genshinImg/Chongyun.png",
    },
    {
        id:13,
        nom:"Collei",
        img:"/img/genshinImg/Collei.png",
    },
    {
        id:14,
        nom:"Cyno",
        img:"/img/genshinImg/Cyno.png",
    },
    {
        id:15,
        nom:"Diluc",
        img:"/img/genshinImg/Diluc.png",
    },
    {
        id:16,
        nom:"Diona",
        img:"/img/genshinImg/Diona.png",
    },
    {
        id:17,
        nom:"Dori",
        img:"/img/genshinImg/Dori.png",
    },
    {
        id:18,
        nom:"Eula",
        img:"/img/genshinImg/Eula.png",
    },
    {
        id:19,
        nom:"Faruzan",
        img:"/img/genshinImg/Faruzan.png",
    },
    {
        id:20,
        nom:"Fischl",
        img:"/img/genshinImg/Fischl.png",
    },
    {
        id:21,
        nom:"Ganyu",
        img:"/img/genshinImg/Ganyu.png",
    },
    {
        id:22,
        nom:"Gorou",
        img:"/img/genshinImg/Gorou.png",
    },
    {
        id:23,
        nom:"Heizou",
        img:"/img/genshinImg/Heizou.png",
    },
    {
        id:24,
        nom:"Hu Tao",
        img:"/img/genshinImg/Hu Tao.png",
    },
    {
        id:25,
        nom:"Itto",
        img:"/img/genshinImg/Itto.png",
    },
    {
        id:26,
        nom:"Jean",
        img:"/img/genshinImg/Jean.png",
    },
    {
        id:27,
        nom:"Kaeya",
        img:"/img/genshinImg/Kaeya.png",
    },
    {
        id:28,
        nom:"Kazuha",
        img:"/img/genshinImg/Kazuha.png",
    },
    {
        id:29,
        nom:"Keqing",
        img:"/img/genshinImg/Keqing.png",
    },
    {
        id:30,
        nom:"Klee",
        img:"/img/genshinImg/Klee.png",
    },
    {
        id:31,
        nom:"Kokomi",
        img:"/img/genshinImg/Kokomi.png",
    },
    {
        id:32,
        nom:"Kuki Shinobu",
        img:"/img/genshinImg/Kuki Shinobu.png",
    },
    {
        id:33,
        nom:"Layla",
        img:"/img/genshinImg/Layla.png",
    },
    {
        id:34,
        nom:"Lisa",
        img:"/img/genshinImg/Lisa.png",
    },
    {
        id:35,
        nom:"Mona",
        img:"/img/genshinImg/Mona.png",
    },
    {
        id:36,
        nom:"Nahida",
        img:"/img/genshinImg/Nahida.png",
    },
    {
        id:37,
        nom:"Nilou",
        img:"/img/genshinImg/Nilou.png",
    },
    {
        id:38,
        nom:"Ningguang",
        img:"/img/genshinImg/Ningguang.png",
    },
    {
        id:39,
        nom:"Noelle",
        img:"/img/genshinImg/Noelle.png",
    },
    {
        id:40,
        nom:"Qiqi",
        img:"/img/genshinImg/Qiqi.png",
    },
    {
        id:41,
        nom:"Raiden",
        img:"/img/genshinImg/Raiden.png",
    },
    {
        id:42,
        nom:"Razor",
        img:"/img/genshinImg/Razor.png",
    },
    {
        id:43,
        nom:"Rosaria",
        img:"/img/genshinImg/Rosaria.png",
    },
    {
        id:44,
        nom:"Sara",
        img:"/img/genshinImg/Sara.png",
    },
    {
        id:45,
        nom:"Sayu",
        img:"/img/genshinImg/Sayu.png",
    },
    {
        id:46,
        nom:"Shenhe",
        img:"/img/genshinImg/Shenhe.png",
    },
    {
        id:47,
        nom:"Sucrose",
        img:"/img/genshinImg/Sucrose.png",
    },
    {
        id:48,
        nom:"Thoma",
        img:"/img/genshinImg/Thoma.png",
    },
    {
        id:49,
        nom:"Tighnari",
        img:"/img/genshinImg/Tighnari.png",
    },
    {
        id:50,
        nom:"Traveler",
        img:"/img/genshinImg/Traveler (Anemo).png",
    },
    {
        id:51,
        nom:"Venti",
        img:"/img/genshinImg/Venti.png",
    },
    {
        id:52,
        nom:"Wanderer",
        img:"/img/genshinImg/Wanderer.png",
    },
    {
        id:53,
        nom:"Xiangling",
        img:"/img/genshinImg/Xiangling.png",
    },
    {
        id:54,
        nom:"Xiao",
        img:"/img/genshinImg/Xiao.png",
    },
    {
        id:55,
        nom:"Xingqiu",
        img:"/img/genshinImg/Xingqiu.png",
    },
    {
        id:56,
        nom:"Xinyan",
        img:"/img/genshinImg/Xinyan.png",
    },
    {
        id:57,
        nom:"Yae Miko",
        img:"/img/genshinImg/Yae Miko.png",
    },
    {
        id:58,
        nom:"Yanfei",
        img:"/img/genshinImg/Yanfei.png",
    },
    {
        id:59,
        nom:"Yaoyao",
        img:"/img/genshinImg/Yaoyao.png",
    },
    {
        id:60,
        nom:"Yelan",
        img:"/img/genshinImg/Yelan.png",
    },
    {
        id:61,
        nom:"Yoimiya",
        img:"/img/genshinImg/Yoimiya.png",
    },
    {
        id:62,
        nom:"Yun Jin",
        img:"/img/genshinImg/Yun Jin.png",
    },
    {
        id:64,
        nom:"Zhongli",
        img:"/img/genshinImg/Zhongli.png",
    },
   ]
}
